---
# Jellyfin role - deploy Jellyfin media server

- name: Copy Jellyfin docker-compose file
  copy:
    src: "{{ playbook_dir }}/../../compose/jellyfin/docker-compose.yml"
    dest: "{{ compose_base_path }}/jellyfin/docker-compose.yml"
    mode: '0644'

- name: Create Jellyfin .env file
  template:
    src: jellyfin.env.j2
    dest: "{{ compose_base_path }}/jellyfin/.env"
    mode: '0600'

- name: Create Jellyfin directories
  file:
    path: "{{ compose_base_path }}/jellyfin/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - config
    - cache

- name: Create media directory
  file:
    path: "{{ jellyfin_media_path | default('/mnt/media') }}"
    state: directory
    mode: '0755'

- name: Start Jellyfin service
  community.docker.docker_compose_v2:
    project_src: "{{ compose_base_path }}/jellyfin"
    state: present
    pull: always
